### ISSUE TITLE
move server state to redis

### ISSUE THREAD

**Issue by radzom** [adorsys/notification-service#4]
to be defined

**Comment by radzom** [comment]
to be defined

**Comment by blazejkrzak** [comment]
I suggest to:

- [ ] write down helm chart for deploy

- [ ] write down docker-compose file to allow write code and work with it in local env

- [ ] atach sdk of redis to allow communication between app and redis

- [ ] pass env variables into container

- [ ] write down pipeline that passes vars

- [ ] refactor code/ change to es6 const/let scope

- [ ] add middleware for each request to write/read state

- [ ] add connections in cache

**Comment by radzom** [comment]
Right now the notification server keeps it connections in a local variable in memory.
https://github.com/adorsys/notification-service/blob/76d0ffbff9854f19a4739459269253405a9089a6/server.js#L17

This will be a problem if the server needs to be scaled horizontally.
If for example 2 notification-servers are running (named A and B) behind a loadbalancer and some app wants to communicate with the notification server it cannot be garanteed to be always A or always B. So if the app first communicates with A and then for a later request the loadbalancer passes the request to B, B does not know about the app since it has no information about it.

Thats why all local state like the communications need to be kept in redis that can be accessed from both A and B.

**Comment by radzom** [comment]
I like the suggestions you made we just don't need new endpoints in the notification server that give access to redis.
Redis should just be accessed from within notification server and not be exposed to the outer world.
